### ISSUE TITLE
Desenvolver uma proposta e implementação para uma visualização da página inicial das vitrinas de conhecimento regional ou local utilizando o plugin do LIS

### ISSUE THREAD

**Issue by marcoslmori** [bireme/lis-wp-plugin#15]
- configurável
	- banner
	- titulo

**Comment by marcoslmori** [comment]
Analisar também como melhoria do plugin

**Comment by marcoslmori** [comment]
Analisar também como melhoria do plugin

**Comment by pintoros** [comment]
Olá, essa página deverá fazer parte no novo Portal Regional para remeter às Vitrines, há alguma previsão para o desenvolvimento?

**Comment by marcoslmori** [comment]
Definir encaminhamentos técnicos com @viniciusandrade  e depois liberação do recurso pelo @renatomurasaki  para o desenvolvimento

**Comment by renatomurasaki** [comment]
Meu entendimento era o cadastramento das vitrines no LIS (aproveitando para indexar no LIS e aumentando a visibilidade por estar no iAHx da BVS Regional) e o uso do plug-in LIS para listar e buscar as vitrines disponíveis. Mudou o escopo?




________________________________
De: Marcos Luis Mori ***@***.***>
Enviado: terça-feira, 22 de junho de 2021 10:43
Para: bireme/lis-wp-plugin ***@***.***>
Cc: Renato Murasaki ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/lis-wp-plugin] Desenvolver uma proposta e implementação para uma visualização da página inicial das vitrinas de conhecimento regional ou local utilizando o plugin do LIS (#15)


Definir encaminhamentos técnicos com @viniciusandrade<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fviniciusandrade&data=04%7C01%7Cmurasaki%40paho.org%7C83c01ac0178a48e3753e08d93583c7d3%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637599662403715865%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=46X8EYPohgdkfJEXFc1gxngRbmVgOVosMgI5GBuZOsk%3D&reserved=0> e depois liberação do recurso pelo @renatomurasaki<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frenatomurasaki&data=04%7C01%7Cmurasaki%40paho.org%7C83c01ac0178a48e3753e08d93583c7d3%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637599662403725819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vAUk3eTemyKosEtHPJDT9Rl1%2FSyxAgq5p9J%2BNa9CFOw%3D&reserved=0> para o desenvolvimento

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Flis-wp-plugin%2Fissues%2F15%23issuecomment-865996185&data=04%7C01%7Cmurasaki%40paho.org%7C83c01ac0178a48e3753e08d93583c7d3%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637599662403725819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=M6fIDzOIO4jGtR1H2rAL3xdhWDG3T0FCOKcUq0E7kqU%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAJLL2VQXNPUMAPXT5NPFCTTUCHRRANCNFSM45PQKOCQ&data=04%7C01%7Cmurasaki%40paho.org%7C83c01ac0178a48e3753e08d93583c7d3%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637599662403735777%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=d4vRp3g%2BtuZoz1fQrxWEmwXTIZxcKK%2B8i6Volyv6rkY%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcoslmori** [comment]
O cadastro já está feito e listado https://bvsalud.org/lis-vitrinas.  Pelo que eu entendi é  ter uma visualização diferente que é proporcionado hoje.

**Comment by renatomurasaki** [comment]
Visualização diferente significa alterar o plug-in do LIS. Primeiro sugiro levantar a necessidade para saber se a visualização diferente pode ser também aplicada ao LIS. Caso não seja, a nossa arquitetura de solução prevê a possibilidade de ter um site WordPress como landing page e dentro deste site a caixa de busca ir para o plug-in do LIS. Esta arquitetura contemplaria a visualização diferente?

Se nenhum dos casos for a resposta para esta mudança, então o plug-in do LIS não é adequado para isso e recomendo iniciar as especificações de arquitetura de informação e funcionalidades, antes de decidirmos pela solução tecnológica.

**Comment by renatomurasaki** [comment]
> Olá, essa página deverá fazer parte no novo Portal Regional para remeter às Vitrines, há alguma previsão para o desenvolvimento?

Entendo que esta página não deva ser dependência para desenvolvimento da nova interface da BVS Regional, pois se trata de outro produto. Vale lembrar que a BVS Regional também é um hub para outros sites ou subsites independentes.

**Comment by pintoros** [comment]
Estou ciente @Murasaki, Renato ***@***.***>, porém solicito prioridade nesse desenvolvimento.
A orientação nesse sentido já data de 2019, quando fizemos 2 reuniões para discutir conteúdo, plugin e foi definido o registro das Vitrines no LIS.  Na época, por solicitação do Dr. Diego para a promoção dessa fonte de informação na OPS, foi desenvolvida a página atual, como solução provisória, até que essa customização da página do LIS para as Vitrines fosse realizado.

Obrigada


Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:6d110376-9834-4ce1-8b15-19212704fe1f]

________________________________
De: Renato Murasaki ***@***.***>
Enviado: quarta-feira, 23 de junho de 2021 12:23
Para: bireme/lis-wp-plugin ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Comment ***@***.***>
Assunto: Re: [bireme/lis-wp-plugin] Desenvolver uma proposta e implementação para uma visualização da página inicial das vitrinas de conhecimento regional ou local utilizando o plugin do LIS (#15)


Olá, essa página deverá fazer parte no novo Portal Regional para remeter às Vitrines, há alguma previsão para o desenvolvimento?

Entendo que esta página não deva ser dependência para desenvolvimento da nova interface da BVS Regional, pois se trata de outro produto. Vale lembrar que a BVS Regional também é um hub para outros sites ou subsites independentes.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Flis-wp-plugin%2Fissues%2F15%23issuecomment-866933626&data=04%7C01%7Cpintoros%40paho.org%7C078f27b9391843d5d3a108d9365ae5c8%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637600586296040457%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=a80NMfnYFFqjuRBHeS7tflnNHUD2lylwE9%2FCI8YcHPk%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4ES3ULSNOYJQQKK54LTUH4AFANCNFSM45PQKOCQ&data=04%7C01%7Cpintoros%40paho.org%7C078f27b9391843d5d3a108d9365ae5c8%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637600586296045431%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7PJSvWCdPzDFECx9NNOHIBH9bek8MHX9rR2PcRH4KfM%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcoslmori** [comment]
O foco do desenvolvimento desse issue será para que seja opcional herdar o cabeçaho do PAI e que possa ter um cabeçalho alternativo e configurável. 
- banner
- titulo

Quanto a visualização dos registros será adotado "ter um site WordPress como landing page e dentro deste site a caixa de busca ir para o plug-in do LIS", conforme está descrito em https://github.com/bireme/wp-vitrines/issues/12

**Comment by marcoslmori** [comment]
Proximos passos - deadline 21/01/22

@marcoslmori  - instalar o tema do portal do lis na instancia de teste do vitrinas do regional  https://teste.bvsalud.org/vitrinas
@marcioalvessilva  e @pierrima - criar página no site e configurar de acordo com arquitetura do portal do lis (https://bvsalud.org/portal-lis/) respeitando os elementos do issue: https://github.com/bireme/wp-vitrines/issues/12

**Comment by marcoslmori** [comment]
Informações importantes que servem para ajudar o desenvolvimento dessa página

Elementos da AI da informação:  https://github.com/bireme/wp-vitrines/issues/12

Outros: 
https://github.com/bireme/wp-vitrines/issues/13

Redirect: pendente: https://github.com/bireme/lis-wp-plugin/issues/14

**Comment by marcoslmori** [comment]
@marcioalvessilva @pierrima tema do portal do lis configurado em https://teste.bvsalud.org/vitrinas/.  
Impacto no banner e no title

**Comment by marcoslmori** [comment]
@marcioalvessilva  Preparado o ambiente para o desenvolvimento da página do portal do LIS na instancia de teste.
- clone da instancia de produção para a teste
- Plugins atualizados inclusive o do vitrinas
- tema do lis instalado
- Plugin do Lis instalado
@pintoros verificar a instancia de teste se com a atualização do plugin não impactou nas vitrinas

Logo após  desenvolvimento da página do lis e validação do conteúdo, deve ser clonado a instancia de teste para produção.

**Comment by pintoros** [comment]
A instância https://teste.bvsalud.org/vitrinas/lis está ok.
É essa ou da vitrine?



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:ec50e766-4fbe-4c49-8a1c-df313ecd93fe]

________________________________
De: Marcos Luis Mori ***@***.***>
Enviado: sábado, 15 de janeiro de 2022 00:30
Para: bireme/lis-wp-plugin ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/lis-wp-plugin] Desenvolver uma proposta e implementação para uma visualização da página inicial das vitrinas de conhecimento regional ou local utilizando o plugin do LIS (#15)


@marcioalvessilva<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarcioalvessilva&data=04%7C01%7Cpintoros%40paho.org%7C1ff35a28437241d9845908d9d7d76d22%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637778142524892376%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YwCcIkQVE3%2FF7ca5d25%2BcMzo%2B7LY%2B3KoN5keCPkoY5I%3D&reserved=0> Preparado o ambiente para o desenvolvimento da página do portal do LIS na instancia de teste.

  *   clone da instancia de produção para a teste
  *   Plugins atualizados inclusive o do vitrinas
  *   tema do lis instalado
  *   Plugin do Lis instalado
@pintoros<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpintoros&data=04%7C01%7Cpintoros%40paho.org%7C1ff35a28437241d9845908d9d7d76d22%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637778142524892376%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JbP2cfy75ZuK8Pl%2BiXd6LUR6dOBlC%2BSPBtSKNshEcdQ%3D&reserved=0> verificar a instancia de teste se com a atualização do plugin não impactou nas vitrinas

Logo após desenvolvimento da página do lis e validação do conteúdo, deve ser clonado a instancia de teste para produção.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Flis-wp-plugin%2Fissues%2F15%23issuecomment-1013599926&data=04%7C01%7Cpintoros%40paho.org%7C1ff35a28437241d9845908d9d7d76d22%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637778142524892376%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=caDTs99YgEVJVywcBal1lAOQ%2FNG3w5OLRA%2F0E0ENkvs%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4FBYA6MWAZAXDNKMK3UWDS6RANCNFSM45PQKOCQ&data=04%7C01%7Cpintoros%40paho.org%7C1ff35a28437241d9845908d9d7d76d22%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637778142524892376%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SyH954odZDuGUOxsDOXPntgfEnsDeUzQ%2Fo4zRmJ4ybU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpintoros%40paho.org%7C1ff35a28437241d9845908d9d7d76d22%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637778142524892376%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bdagx72XFkUrk9ykd9TXXyjAhrKfcFdbZ0wKY%2BRx918%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpintoros%40paho.org%7C1ff35a28437241d9845908d9d7d76d22%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637778142524892376%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=o6y2Izec2dgps26Lc5Cw77qhPexfXyD611JS581veiw%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcoslmori** [comment]
Oi @pintoros São as vitrines da instancia de teste:  https://teste.bvsalud.org/vitrinas/post_vitrines/

Vi, por exemplo,  que os banners estão errado.  @marcioalvessilva 

Mas creio que o Marcio está trabalhando nisso agora

Abraços,

**Comment by pintoros** [comment]
@wilsonmoura @marcoslmori 
Favor inserir na página https://teste.bvsalud.org/vitrinas/lis o menu de navegação por idioma.
Obrigada

**Comment by wilsonmoura** [comment]
Resolvido bug relacionado com a exibição do menu de idiomas do Polylang. Correção aplicada em #20.

**Comment by wilsonmoura** [comment]
URL do Portal de Vitrines: https://bvsalud.org/vitrinas/
